<hr>
<div class="row">
	<div class="span4">
		<h3>O autorze</h3>
		<p><a href="/public/cv/CV_Lukasz_Szura.pdf">Moje CV</a></p>
		
	</div>
	<div class="span4">
		<h4>O aplikacji</h4>
		<p>Głównym celem aplikacji jest skracanie długich adresów url.</p>
		<p> Zajerestrowany użytkownik ma możliwość:
			<ul>
				<li>Wglądu do bazy swoih linków</li>
				<li>Usuwania adresów</li>
				<li>Generowania kodów QR na urządzenia mobilne</li>
				<li>Podgląd aktywności danego adresu.</li>
			</ul>
		</p>
	</div>
	<div class="span4">
		<h4>Wykorzystane technologie</h4>
		<p>W aplikacji wykorzystano następujące frameworki:</p>
		<p>
		<a href="http://framework.zend.com/"><img src="http://framework.zend.com/images/logo_small.gif"/></a><br/>
		<a href="http://jquery.com/"><img src="/public/icon/icon_jq.jpg"/></a><br/>
		<a href="http://twitter.github.com/bootstrap/"><img src="/public/icon/icon_bt.png"/></a><br/>
		</p>
	</div>
</div>