<script type="text/javascript">
$().ready(function(){
    $("#nowehaslo").validate({
        rules:{
            email:{
                required: true,
                email: true
            }
        },
        messages:{
            email:{
               required:"<i class='icon-exclamation-sign'></i><font color='red'> Wpisz adres email.</font>",
              email:"<i class='icon-exclamation-sign'></i><font color='red'> Podaj poprawny adres email.</font>"
            }
        }
    });
})

</script>
<?  $this->form_new_haslo->setAttrib('id', 'nowehaslo')
				->setAttrib('class','well');
echo $this->form_new_haslo;

?>