<script type="text/javascript">
$(document).ready(function(){
  $("#nowyuser").validate({
        rules:{
            imie:{
                required: true                
            },
            nazwisko:{
                required: true
            },
            email_u:{
                required: true,
                remote: "/public/index/checkemail" 
            },
            haslo:{
                required: true,
                minlength: 6
            },
            haslo1:{
                equalTo: "#haslo"                
            }
        },
        messages:{
            imie:{
                required: "<i class='icon-exclamation-sign'></i><font color='red'> Wpisz imi\u0119.</font>"
                },
            nazwisko:{
                required: "<i class='icon-exclamation-sign'></i><font color='red'> Wpisz nazwisko.</font>"
                },
            email_u:{
                required: "<i class='icon-exclamation-sign'></i><font color='red'> Wpisz adres email.</font>",
                remote: "<i class='icon-exclamation-sign'></i><font color='red'> Podany email jest ju\u017c zajęty lub niepoprawny</font>"
                },
            haslo:{
                required: "<i class='icon-exclamation-sign'></i><font color='red'> Wpisz has\u0142o.</font>",
                minlength: "<i class='icon-exclamation-sign'></i><font color='red'> Has\u0142o powino zawierać minimum 6 znaków.</font>"
                },
            haslo1:{
                equalTo: "<i class='icon-exclamation-sign'></i><font color='red'> Wpisz takie samo has\u0142o.</font>"
                }
        }
    }) 
});

</script>
<style type="text/css">
    .error{
        color: red;
    }
    
</style>
<? $this->nowy->setAttribs(array(
            'id'    => 'nowyuser',
            'class' => 'well'
        ));
   $this->nowy->submit->setAttrib('class','btn btn-large btn-primary');

 ?>

<div class="row">
    <div class="span4 offset4">
        <?  
            if(isset($this->error)){
            echo "
                <script type=\"text/javascript\">
                $(\".alert\").alert()
                </script>
                <div class=\"alert alert-block alert-error fade in\">
                <a class=\"icon-remove-circle close\" data-dismiss=\"alert\" href=\"#\"></a>
                <h4>Wiadomość</h4>
                <p>".$this->error."</p>

                </div>
                 ";    
            }
        ?>
        <?= $this->nowy; ?> 
    </div>
</div>   


