<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="/public/icon/cut.png">
        <?= $this->headMeta()->appendHttpEquiv('Content-Type','text/html; charset=utf-8');?>
		<?= $this->headTitle('Skruć link') ?>
        <?  $this->headScript()->appendFile('http://code.jquery.com/jquery.js');?>
        <?= $this->headScript()->appendFile('http://ajax.microsoft.com/ajax/jquery.validate/1.7/jquery.validate.min.js');?>
        <!-- Le styles -->
        <link href="/public/assets/css/bootstrap.css" rel="stylesheet">
        <link href="/public/assets/css/bootstrap-responsive.css" rel="stylesheet">
        <link href="/public/assets/css/docs.css" rel="stylesheet">
        <link href="/public/assets/js/google-code-prettify/prettify.css" rel="stylesheet">

        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <!-- Le javascript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
        
        <script src="/public/assets/js/google-code-prettify/prettify.js"></script>
        <script src="/public/assets/js/bootstrap-transition.js"></script>
        <script src="/public/assets/js/bootstrap-alert.js"></script>
        <script src="/public/assets/js/bootstrap-modal.js"></script>
        <script src="/public/assets/js/bootstrap-dropdown.js"></script>
        <script src="/public/assets/js/bootstrap-scrollspy.js"></script>
        <script src="/public/assets/js/bootstrap-tab.js"></script>
        <script src="/public/assets/js/bootstrap-tooltip.js"></script>
        <script src="/public/assets/js/bootstrap-popover.js"></script>
        <script src="/public/assets/js/bootstrap-button.js"></script>
        <script src="/public/assets/js/bootstrap-collapse.js"></script>
        <script src="/public/assets/js/bootstrap-carousel.js"></script>
        <script src="/public/assets/js/bootstrap-typeahead.js"></script>
        <script src="/public/assets/js/application.js"></script>
        <script src="http://code.highcharts.com/highcharts.js"></script>
        <script src="http://code.highcharts.com/modules/exporting.js"></script>
        
        <style type="text/css">
          body {
            padding-top: 60px;
            padding-bottom: 40px;
          }
        </style>
        <script type="text/javascript">
            $().ready(function(){
                    
            });
        </script>
		<script type="text/javascript">

			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-19988651-5']);
			_gaq.push(['_trackPageview']);

			(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();

		</script>
    </head>
    
    
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    
                    <div class="nav-collapse">
                            <ul class="nav">
                                <li><a href="/">Home</a></li>
                                <?
                                if(!Zend_Auth::getInstance()->hasIdentity()){
                                    echo "<li><a href=\"/public/logowanie/nowyuser\">Zarejestruj się</a></li>";
                                    echo "<li><a href=\"/public/logowanie/nowehaslo\">Przypomnij hasło</a></li>";
                                
                                    
                                }    
                                ?>
                                
                            </ul>
                            
                    </div>
                    <?
                    if(Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == "index")
                        echo $this->action('zaloguj','logowanie');
                    ?>
                </div>
            </div>
        </div>

        <div class="container">
             <?php echo $this->layout()->content; ?>
        
        
            <?= $this->action('test','index'); ?>
            <? if(Zend_Auth::getInstance()->hasIdentity())
                    echo $this->action('dane','index'); 
				else
					echo $this->render('index/info.phtml');
			?>
        </div>
        <div id="myModal" class="modal hide fade" style="display: none; ">
            <div class="modal-header">
                <a class="close btn-inverse btn-large" data-dismiss="modal">×</a>
                <h2>Zmiana hasła</h2>
            </div>
            <div class="modal-body">
                <?
                if(Zend_Controller_Front::getInstance()->getRequest()->getControllerName() != "logowanie")
                echo $this->action('zmianahasla','logowanie');
                ?>
            </div>
        </div>
       
    </body>
    
</html>



